# Generated by Django 3.0.3 on 2020-05-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200426_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('False', 'Hayır'), ('New', 'Yeni'), ('True', 'Evet')], default='New', max_length=10),
        ),
    ]
