# Generated by Django 3.0.3 on 2020-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_order_orderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_buy', models.CharField(max_length=10)),
                ('day', models.IntegerField()),
            ],
        ),
    ]
