# Generated by Django 3.0.3 on 2020-05-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_calculate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='day',
            field=models.FloatField(),
        ),
    ]
