# Generated by Django 3.0.3 on 2020-05-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200509_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
