# Generated by Django 3.0.3 on 2020-05-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_order_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='instagram',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='twitter',
            new_name='linkedin',
        ),
    ]
