# Generated by Django 3.0.3 on 2020-05-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='ordernmbr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
    ]
