# Generated by Django 3.0.3 on 2020-05-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200515_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
