# Generated by Django 3.0.3 on 2020-05-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200515_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
