# Generated by Django 3.0.3 on 2020-05-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200515_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.CharField(max_length=30),
        ),
    ]
