# Generated by Django 3.0.3 on 2020-05-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200515_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='date_start',
            field=models.DateField(),
        ),
    ]
