# Generated by Django 3.0.3 on 2020-05-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200515_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='date_end',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='date_start',
            field=models.CharField(max_length=50),
        ),
    ]
