# Generated by Django 3.0.3 on 2020-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200521_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
